backend:
   name: github
   repo: smokeyfro/website
   branch: main
   base_url: https://sveltia-cms-auth.chris-a04.workers.dev

site_url: https://new.smokeyfro.com
display_url: https://new.smokeyfro.com
logo_url: https://smokeyfro.com/favicon.png

media_folder: public/media
public_folder: /media

media_library:
  name: cloudinary
  config:
    cloud_name: smokeyfro
    api_key: 986198746664826
    
collections:
  - name: work
    label: Work
    folder: content/work
    icon: collections_bookmark
    media_folder: /public/media/work
    public_folder: /media/work
    format: frontmatter
    create: true
    slug: {{slug}}
    editor:
      preview: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Url
        name: url
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Services
        name: service
        widget: relation
        collection: service
        search_fields: [title]
        value_field: title
        display_fields: [title]
        multiple: true
      - label: Tags
        name: tags
        widget: list
      - label: Type
        name: type
        widget: relation
        collection: type
        search_fields: [title]
        value_field: title
        display_fields: [title]
      - label: Image
        name: image
        widget: image
      - label: Gallery
        name: gallery
        widget: list
        required: false
        collapsed: true
        fields:
          - label: Thumb
            name: thumbnail
            widget: image
          - label: Source
            name: src
            widget: image
          - label: Alt
            name: alt
            widget: string
          - label: Title
            name: title
            widget: string
      - label: Body
        name: body
        widget: markdown
  - name: type
    label: Types
    folder: content/types
    icon: collections_bookmark
    format: frontmatter
    create: true
    slug: {{slug}}
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: service
    label: Services
    folder: content/services
    icon: collections_bookmark
    format: frontmatter
    create: true
    slug: {{slug}}
    editor:
      preview: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown