backend:
  name: github
  repo: smokeyfro/website
  branch: main
  base_url: https://sveltia-cms-auth.chris-a04.workers.dev
media_folder: public/media
public_folder: /media
collections:
  - name: 'journal'
    label: 'Journal'
    folder: 'content/journal'
    media_folder: '/static/media/journal'
    public_folder: '/media/journal'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    media_folder: /static/media/work
    public_folder: /media/work
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Featured Image"
        name: "image"
        widget: "image"
        choose_url: true
  - name: 'services'
    label: 'Services'
    folder: 'content/services'
    media_folder: /static/media/services
    public_folder: /media/services
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'photos'
    label: 'Photos'
    folder: 'content/photos'
    media_folder: /static/media/photos
    public_folder: /media/photos
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'release-notes'
    label: 'Release Notes'
    folder: 'content/release-notes'
    media_folder: /static/media/release-notes
    public_folder: /media/release-notes
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'themes'
    label: 'Themes'
    folder: 'content/themes'
    media_folder: /static/media/themes
    public_folder: /media/themes
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'tutorials'
    label: 'Tutorials'
    folder: 'content/tutorials'
    media_folder: /static/media/tutorials
    public_folder: /media/tutorials
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'videos'
    label: 'Videos'
    folder: 'content/videos'
    media_folder: /static/media/videos
    public_folder: /media/videos
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }